import { useEffect, useMemo, useState } from 'react'
import { adminRequest } from '../admin/api'
import { formatDate, invitationLabel, metric, periodOptions } from '../admin/metrics'
import type { AdminInvitation, AdminMatch, AdminPage as Page, AdminRoster, AdminSection, AdminSummary, AdminUser, PeriodPreset } from '../admin/types'

type LoadState = 'loading' | 'ready' | 'denied' | 'error'

const sectionLabels: Array<[AdminSection, string]> = [['summary', 'Resumen'], ['adoption', 'Uso'], ['users', 'Usuarios'], ['rosters', 'Planteles'], ['matches', 'Partidos'], ['invitations', 'Invitaciones']]
const positionLabel: Record<string, string> = { goalkeeper: 'Arquero', defender: 'Defensor', midfielder: 'Mediocampista', forward: 'Delantero' }

function Status({ kind, children }: { kind: 'exact' | 'inferred' | 'unavailable'; children: React.ReactNode }) { return <p className={`admin-definition ${kind}`}><strong>{kind === 'exact' ? 'Exacta' : kind === 'inferred' ? 'Inferida' : 'No disponible'}</strong>{children}</p> }
function Kpi({ label, value, hint, priority = false }: { label: string; value: number | null; hint: string; priority?: boolean }) { return <article className={`admin-kpi${priority ? ' priority' : ''}`}><p>{label}</p><strong>{metric(value)}</strong><small>{hint}</small></article> }
function Signal({ label, value, detail, tone = 'neutral' }: { label: string; value: number | null; detail: string; tone?: 'neutral' | 'attention' | 'muted' }) { return <article className={`admin-signal ${tone}`}><div><p>{label}</p><small>{detail}</small></div><strong>{metric(value)}</strong></article> }
function Chart({ summary }: { summary: AdminSummary }) {
  const max = Math.max(1, ...summary.series.flatMap((entry) => [entry.users, entry.rosters, entry.players, entry.matches, entry.completed, entry.invitationsAccepted]))
  const points = (field: keyof AdminSummary['series'][number]) => summary.series.map((entry, index) => `${summary.series.length < 2 ? 50 : index / (summary.series.length - 1) * 100},${92 - Number(entry[field]) / max * 82}`).join(' ')
  const legends: Array<[keyof AdminSummary['series'][number], string]> = [['users', 'Altas'], ['rosters', 'Planteles'], ['players', 'Jugadores'], ['matches', 'Partidos creados'], ['completed', 'Partidos completos'], ['invitationsAccepted', 'Invitaciones aceptadas']]
  return <section className="panel admin-chart" aria-labelledby="admin-series-title"><div className="panel-heading"><div><p className="eyebrow">EVOLUCIÓN</p><h2 id="admin-series-title">Registros por día</h2></div></div>{summary.series.length ? <><svg viewBox="0 0 100 100" role="img" aria-label={`Series diarias del período ${summary.range.label}. Máximo diario: ${max}.`} preserveAspectRatio="none">{legends.map(([field], index) => <polyline key={String(field)} className={`admin-line line-${index}`} points={points(field)} />)}</svg><ul className="admin-legend">{legends.map(([field, label], index) => <li key={String(field)}><i className={`line-${index}`} />{label}</li>)}</ul><details><summary>Alternativa textual</summary><ul>{summary.series.map((entry) => <li key={entry.date}>{formatDate(entry.date)}: {entry.users} altas, {entry.rosters} planteles, {entry.players} jugadores, {entry.matches} partidos, {entry.completed} completos y {entry.invitationsAccepted} invitaciones aceptadas.</li>)}</ul></details></> : <p className="muted">No hay actividad persistida en este período.</p>}</section>
}

function Summary({ summary }: { summary: AdminSummary }) {
  const k = summary.kpis
  return <><section className="admin-executive-overview" aria-labelledby="admin-overview-title"><div className="admin-overview-heading"><div><p className="eyebrow">PANORAMA EJECUTIVO</p><h2 id="admin-overview-title">Estado del producto</h2></div><p>Indicadores principales y señales para leer el período de un vistazo.</p></div><div className="admin-executive-grid"><section className="admin-primary-metrics" aria-label="Indicadores principales"><div className="admin-primary-kpis"><Kpi priority label="Usuarios registrados" value={k.registeredUsers} hint={`${metric(k.registeredUsersInPeriod)} altas en el período`} /><Kpi priority label="Planteles" value={k.rosters} hint={`${metric(k.rostersCreated)} creados en el período`} /><Kpi priority label="Partidos completos" value={k.completedMatches} hint={`${metric(k.matchesCreated)} creados en el período`} /><Kpi priority label="Finalización" value={k.completionRate} hint="Completos sobre creados" /></div></section><aside className="admin-signals" aria-label="Señales operativas"><div><p className="eyebrow">SEÑALES OPERATIVAS</p><h3>Para seguir de cerca</h3></div><Signal label="Invitaciones pendientes" value={k.pending} detail="Esperan una respuesta" tone="attention" /><Signal label="Partidos sin resultado" value={summary.distributions.results.withoutResult} detail="Todavía no registran cierre" tone="attention" /><Signal label="Jugadores archivados" value={k.archivedPlayers} detail="Fuera del plantel activo" tone="muted" /></aside></div></section><section className="admin-secondary-metrics" aria-labelledby="admin-secondary-metrics-title"><div><p className="eyebrow">CONTEXTO DEL PERÍODO</p><h2 id="admin-secondary-metrics-title">Indicadores de soporte</h2></div><div className="admin-kpis"><Kpi label="Accesos recientes" value={k.recentSignIns} hint="last_sign_in_at de Auth" /><Kpi label="Jugadores activos" value={k.activePlayers} hint={`${metric(k.playersPerRoster)} por plantel`} /><Kpi label="Partidos creados" value={k.matchesCreated} hint={`${metric(k.confirmedMatches)} confirmados`} /><Kpi label="Invitaciones" value={k.invitationsCreated} hint={`${metric(k.accepted)} aceptadas · ${metric(k.expired)} vencidas`} /><Kpi label="Tamaño de equipo" value={k.averageTeamSize} hint="Promedio de partidos creados" /></div></section><Chart summary={summary} /><section className="panel"><p className="eyebrow">ALCANCE DE LOS DATOS</p><h2>Cómo leer este tablero</h2><div className="admin-definitions">{summary.definitions.map((definition) => <Status kind={definition.kind} key={definition.text}>{definition.text}</Status>)}</div></section></>
}

function Adoption({ summary }: { summary: AdminSummary }) {
  const totalPlayers = summary.distributions.positions.reduce((sum, item) => sum + item.count, summary.distributions.withoutPosition)
  const rows = [{ label: 'Registro', count: summary.adoption.registered }, { label: 'Plantel con actividad', count: summary.adoption.rosterActivity }, { label: 'Plantel con jugador', count: summary.adoption.rosterWithPlayer }, { label: 'Plantel con partido', count: summary.adoption.rosterWithMatch }, { label: 'Plantel con resultado', count: summary.adoption.rosterWithResult }]
  return <section className="admin-grid"><section className="panel"><p className="eyebrow">ACTIVIDAD INFERIDA</p><h2>Embudo de adopción</h2><p className="muted">Después del registro, la actividad se atribuye al plantel, no a una persona en planteles compartidos.</p><ol className="admin-funnel">{rows.map((row, index) => <li key={row.label}><span>{index + 1}</span><strong>{row.label}</strong><b>{metric(row.count)}</b></li>)}</ol></section><section className="panel"><p className="eyebrow">PLANTELES</p><h2>Jugadores activos por plantel</h2><ul className="admin-bars">{summary.distributions.playersPerRoster.map((item) => <li key={item.label}><span>{item.label}</span><i style={{ width: `${Math.max(4, item.count / Math.max(1, ...summary.distributions.playersPerRoster.map((entry) => entry.count)) * 100)}%` }} /><b>{item.count}</b></li>)}</ul></section><section className="panel"><p className="eyebrow">JUGADORES</p><h2>Posiciones y rendimiento</h2><ul className="admin-compact-list">{summary.distributions.positions.map((item) => <li key={item.position}>{positionLabel[item.position]} <b>{item.count}</b></li>)}<li>Sin posición <b>{summary.distributions.withoutPosition} ({totalPlayers ? metric(summary.distributions.withoutPosition / totalPlayers * 100, '%') : '—'})</b></li></ul><hr /><ul className="admin-compact-list">{summary.distributions.performance.map((item) => <li key={item.label}>{item.label} <b>{item.count}</b></li>)}</ul></section><section className="panel"><p className="eyebrow">PARTIDOS</p><h2>Escala y operación</h2><ul className="admin-compact-list">{summary.distributions.ratingScale.map((item) => <li key={item.scale}>Elo {item.scale} <b>{item.count}</b></li>)}<li>Con resultado <b>{summary.distributions.results.withResult}</b></li><li>Sin resultado <b>{summary.distributions.results.withoutResult}</b></li><li>Confirmados hace +7 días <b>{summary.distributions.results.staleConfirmed}</b></li></ul><p className="muted">La última fila es una señal operativa, no un error.</p></section></section>
}

function Pager({ data, onChange }: { data: Page<unknown>; onChange: (page: number) => void }) { return <footer className="admin-pager"><span>{data.total} registros · página {data.page} de {data.totalPages}</span><button type="button" disabled={data.page <= 1} onClick={() => onChange(data.page - 1)}>Anterior</button><button type="button" disabled={data.page >= data.totalPages} onClick={() => onChange(data.page + 1)}>Siguiente</button></footer> }
function Search({ value, onChange, label }: { value: string; onChange: (value: string) => void; label: string }) { return <label className="admin-search">{label}<input value={value} onChange={(event) => onChange(event.target.value)} placeholder="Buscar…" /></label> }

function ListSection({ section, range, onDetail }: { section: Exclude<AdminSection, 'summary' | 'adoption'>; range: AdminSummary['range']; onDetail: (action: 'user-detail' | 'roster-detail' | 'match-detail', id: string) => void }) {
  const [query, setQuery] = useState(''), [page, setPage] = useState(1), [data, setData] = useState<Page<AdminUser | AdminRoster | AdminMatch | AdminInvitation> | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true), [reload, setReload] = useState(0), [status, setStatus] = useState(''), [scale, setScale] = useState(''), [teamSize, setTeamSize] = useState(''), [invitationStatus, setInvitationStatus] = useState('')
  useEffect(() => { setPage(1) }, [section, query])
  useEffect(() => { let active = true; setLoading(true); setError(null); const filters = section === 'matches' ? { from: range.from, to: range.to, status: status || undefined, ratingScale: scale || undefined, teamSize: teamSize || undefined } : section === 'invitations' ? { status: invitationStatus || undefined } : undefined; void adminRequest<Page<AdminUser | AdminRoster | AdminMatch | AdminInvitation>>(section, { query, page, pageSize: 20, filters }).then((next) => { if (active) setData(next) }).catch((reason: Error) => { if (active) setError(reason.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [section, query, page, range.from, range.to, status, scale, teamSize, invitationStatus, reload])
  const rows = data?.items ?? []
  return <section className="panel admin-table-panel"><div className="panel-heading"><div><p className="eyebrow">LISTADO PROTEGIDO</p><h2>{section === 'users' ? 'Usuarios' : section === 'rosters' ? 'Planteles' : section === 'matches' ? 'Partidos' : 'Invitaciones'}</h2></div></div><div className="admin-table-filters"><Search value={query} onChange={setQuery} label={section === 'invitations' ? 'Buscar plantel o creador' : section === 'matches' ? 'Buscar plantel' : 'Buscar'} />{section === 'matches' && <><label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option><option value="confirmed">Confirmado</option><option value="completed">Completo</option></select></label><label>Escala Elo<select value={scale} onChange={(event) => setScale(event.target.value)}><option value="">Todas</option><option value="10">10</option><option value="100">100</option></select></label><label>Tamaño<select value={teamSize} onChange={(event) => setTeamSize(event.target.value)}><option value="">Todos</option>{[1, 2, 3, 4, 5, 6, 7, 8].map((size) => <option value={size} key={size}>{size}</option>)}</select></label></>}{section === 'invitations' && <label>Estado<select value={invitationStatus} onChange={(event) => setInvitationStatus(event.target.value)}><option value="">Todos</option><option value="accepted">Aceptada</option><option value="pending">Pendiente</option><option value="expired">Vencida</option></select></label>}</div>{loading ? <p className="admin-state" role="status">Cargando datos administrativos…</p> : error ? <p className="admin-state error">{error} <button type="button" onClick={() => setReload((current) => current + 1)}>Reintentar</button></p> : !rows.length ? <p className="admin-state">No hay registros para estos filtros.</p> : <div className="admin-table-scroll"><table><thead>{section === 'users' ? <tr><th>Identidad</th><th>Registro</th><th>Último acceso</th><th>Planteles</th><th>Partidos</th><th /></tr> : section === 'rosters' ? <tr><th>Plantel</th><th>Dueño</th><th>Jugadores</th><th>Partidos</th><th>Último partido</th><th /></tr> : section === 'matches' ? <tr><th>Fecha</th><th>Plantel</th><th>Estado</th><th>Escala</th><th>Resultado</th><th /></tr> : <tr><th>Estado</th><th>Plantel</th><th>Creador</th><th>Creada</th><th>Vence</th></tr>}</thead><tbody>{rows.map((row) => section === 'users' ? <UserRow key={row.id} user={row as AdminUser} onDetail={onDetail} /> : section === 'rosters' ? <RosterRow key={row.id} roster={row as AdminRoster} onDetail={onDetail} /> : section === 'matches' ? <MatchRow key={row.id} match={row as AdminMatch} onDetail={onDetail} /> : <InvitationRow key={row.id} invitation={row as AdminInvitation} />)}</tbody></table></div>}{data && <Pager data={data} onChange={setPage} />}</section>
}
function UserRow({ user, onDetail }: { user: AdminUser; onDetail: (action: 'user-detail' | 'roster-detail' | 'match-detail', id: string) => void }) { return <tr><td><strong>{user.name ?? 'Sin nombre'}</strong><small>{user.email ?? 'Sin email'}</small></td><td>{formatDate(user.createdAt)}</td><td>{formatDate(user.lastSignInAt)}</td><td>{user.rosterCount}</td><td>{user.matchesInRosters}</td><td><button type="button" onClick={() => onDetail('user-detail', user.id)}>Ver</button></td></tr> }
function RosterRow({ roster, onDetail }: { roster: AdminRoster; onDetail: (action: 'roster-detail', id: string) => void }) { return <tr><td>{roster.name ?? 'Sin nombre'}</td><td>{roster.owner.name ?? roster.owner.email ?? 'Sin dato'}</td><td>{roster.activePlayers} activos</td><td>{roster.matches} · {metric(roster.completionRate, '%')}</td><td>{formatDate(roster.lastMatchAt)}</td><td><button type="button" onClick={() => onDetail('roster-detail', roster.id)}>Ver</button></td></tr> }
function MatchRow({ match, onDetail }: { match: AdminMatch; onDetail: (action: 'match-detail', id: string) => void }) { return <tr><td>{formatDate(match.createdAt)}</td><td>{match.roster.name}</td><td><span className={`admin-status ${match.status}`}>{match.status === 'completed' ? 'Completo' : 'Confirmado'}</span></td><td>{match.ratingScale}</td><td>{match.result ? `${match.result.outcome} · Δ${match.result.goalDifference ?? '—'}` : 'Sin resultado'}</td><td><button type="button" onClick={() => onDetail('match-detail', match.id)}>Ver</button></td></tr> }
function InvitationRow({ invitation }: { invitation: AdminInvitation }) { return <tr><td><span className={`admin-status ${invitation.status}`}>{invitationLabel(invitation.status)}</span></td><td>{invitation.roster}</td><td>{invitation.creator.name ?? invitation.creator.email ?? 'Sin dato'}</td><td>{formatDate(invitation.createdAt)}</td><td>{formatDate(invitation.expiresAt)}</td></tr> }

function Detail({ detail, onClose }: { detail: Record<string, unknown>; onClose: () => void }) { return <section className="panel admin-detail" aria-live="polite"><div className="panel-heading"><div><p className="eyebrow">DETALLE PROTEGIDO</p><h2>{String(detail.name ?? detail.email ?? detail.id)}</h2></div><button type="button" onClick={onClose}>Cerrar</button></div>{Array.isArray(detail.members) && <section><h3>Miembros</h3><ul>{(detail.members as Array<{ name: string | null; email: string | null }>).map((member, index) => <li key={index}>{member.name ?? member.email ?? 'Sin identidad disponible'}</li>)}</ul></section>}{Array.isArray(detail.players) && <section><h3>Jugadores</h3><ul>{(detail.players as Array<{ id: string; name: string; archived: boolean; position: string | null }>).map((player) => <li key={player.id}>{player.name} · {player.archived ? 'Archivado' : positionLabel[player.position ?? ''] ?? 'Sin posición'}</li>)}</ul></section>}{Array.isArray(detail.rosters) && <section><h3>Planteles</h3><ul>{(detail.rosters as AdminRoster[]).map((roster) => <li key={roster.id}>{roster.name ?? 'Sin nombre'} · {roster.matches} partidos</li>)}</ul></section>}{Array.isArray(detail.matches) && <section><h3>Últimos partidos</h3><ul>{(detail.matches as AdminMatch[]).map((match) => <li key={match.id}>{formatDate(match.createdAt)} · {match.status === 'completed' ? 'Completo' : 'Confirmado'} · {match.result ? match.result.outcome : 'Sin resultado'}</li>)}</ul></section>}{Array.isArray(detail.teams) && <section><h3>Equipos</h3><div className="admin-teams">{(detail.teams as Array<Array<{ player: { id: string; name: string; position: string | null }; ratingOffset: number; performanceRating: number }>>).map((team, index) => <ol key={index}><strong>Equipo {index + 1}</strong>{team.map((participant) => <li key={participant.player.id}>{participant.player.name} · {positionLabel[participant.player.position ?? ''] ?? 'Sin posición'} · Elo {metric(participant.ratingOffset)} · rendimiento {participant.performanceRating}</li>)}</ol>)}</div></section>}</section> }

export default function AdminPage({ onExit }: { onExit: () => void }) {
  const [state, setState] = useState<LoadState>('loading'), [summary, setSummary] = useState<AdminSummary | null>(null), [section, setSection] = useState<AdminSection>('summary'), [preset, setPreset] = useState<PeriodPreset>('30d'), [from, setFrom] = useState(''), [to, setTo] = useState(''), [detail, setDetail] = useState<Record<string, unknown> | null>(null)
  const load = () => { setState('loading'); void Promise.all([adminRequest<{ isAdmin: boolean }>('access'), adminRequest<AdminSummary>('summary', { preset, from: from || undefined, to: to || undefined })]).then(([access, next]) => { if (!access.isAdmin) setState('denied'); else { setSummary(next); setState('ready') } }).catch((reason: Error) => setState(reason.message.includes('permiso') ? 'denied' : 'error')) }
  useEffect(load, [preset, from, to])
  const queryRange = useMemo(() => summary?.range ?? { preset, from: preset === 'custom' ? from : null, to: preset === 'custom' ? to : null, label: 'Período seleccionado' }, [summary, preset, from, to])
  const loadDetail = (action: 'user-detail' | 'roster-detail' | 'match-detail', id: string) => { setDetail(null); void adminRequest<Record<string, unknown>>(action, { id }).then(setDetail).catch(() => setDetail({ name: 'No se pudo cargar el detalle' })) }
  if (state === 'loading') return <section className="admin-page"><p className="admin-state" role="status">Verificando permisos y cargando el tablero…</p></section>
  if (state === 'denied') return <section className="admin-page"><section className="panel admin-access-message"><p className="eyebrow">ADMINISTRACIÓN</p><h2>No tenés permiso para acceder a esta sección</h2><p>No se cargó ningún dato administrativo.</p><button type="button" onClick={onExit}>Volver a Fulbo Parejo</button></section></section>
  if (state === 'error' || !summary) return <section className="admin-page"><section className="panel admin-access-message"><p className="eyebrow">ADMINISTRACIÓN</p><h2>No se pudo cargar el tablero</h2><p>Revisá la conexión e intentá nuevamente.</p><button type="button" onClick={load}>Reintentar</button><button type="button" onClick={onExit}>Volver</button></section></section>
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">DASHBOARD INTERNO · SOLO LECTURA</p><h1>Administración</h1><p>{summary.range.label} · datos actualizados al consultar</p></div><button type="button" onClick={onExit}>Salir</button></header><section className="admin-filters"><label>Período<select value={preset} onChange={(event) => setPreset(event.target.value as PeriodPreset)}>{periodOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>{preset === 'custom' && <><label>Desde<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>Hasta (excl.)<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></>}</section><nav className="admin-nav" aria-label="Secciones administrativas">{sectionLabels.map(([key, label]) => <button type="button" className={section === key ? 'active' : ''} aria-current={section === key ? 'page' : undefined} key={key} onClick={() => { setSection(key); setDetail(null) }}>{label}</button>)}</nav>{section === 'summary' && <Summary summary={summary} />}{section === 'adoption' && <Adoption summary={summary} />}{(['users', 'rosters', 'matches', 'invitations'] as AdminSection[]).includes(section) && <ListSection section={section as Exclude<AdminSection, 'summary' | 'adoption'>} range={queryRange} onDetail={loadDetail} />}{detail && <Detail detail={detail} onClose={() => setDetail(null)} />}</main>
}

